config/routes.rb
SmartBlog::Application.routes.draw do

  get "artfolio/index/:genre" => 'artfolio#index'
  get "artfolio/index"

  get "blogposts/display/:genre" => 'blogposts#display'
  get "blogposts/display" => 'blogposts#display'

  get "resume/show"
  get "resume/about"
  get "resume/lang"
  get "resume/work"
  get "resume/edu"
  get "/resume/relevant"

  get "about/show"

  get "contact/show"

  get "bigdata/index"

  root :to => 'resume#show'

end

app/models/art_folio.rb
class ArtFolio < ActiveRecord::Base
end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
  attr_accessible :category, :content, :image, :title, :image_text, :date
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  layout "nonavcenter"
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artfolio_controller.rb
class ArtfolioController < ApplicationController
  def index
    genre = "oilpainting"
    if params[:genre]
      genre = params[:genre]
    end
    @artworks = ArtFolio.where("genre = ?", genre).page params[:page]
    respond_to do |format|
      format.js   {}
      format.html { render "index" }
    end
  end
end

app/controllers/bigdata_controller.rb
class BigdataController < ApplicationController
  layout "custom"
  def index
  end
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  layout "custom"

  def display
    category = "tech"
    if params[:genre]
      category = params[:genre]
    end
    @blogposts = Blogpost.where("category = ?", category)

    respond_to do |format|
      format.js   {}
      format.html { render "display" }
    end
  end

  def index
    @blogposts = Blogpost.all
  end

  def show
    @post = Blogpost.find(params[:id])
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Blogpost.new
  end

  # GET /posts/1/edit
  def edit
    @post = Blogpost.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Blogpost.new(params[:blogpost])

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render action: "new"
    end

  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Blogpost.find(params[:id])
    if @post.update_attributes(params[:blogpost])
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Blogpost.find(params[:id])
    @post.destroy
    redirect_to blogposts_url
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  layout "nonavcenter"
  def show
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def show
  end

  def about
    respond_to do |format|
      format.js   {}
      format.html { render "about" }
    end
  end

  def lang
    respond_to do |format|
      format.js   {}
      format.html { render "lang" }
    end
  end

  def work
    respond_to do |format|
      format.js   {}
      format.html { render "work" }
    end
  end

  def edu
    respond_to do |format|
      format.js   {}
      format.html { render "edu" }
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artfolio_helper.rb
module ArtfolioHelper
end

app/helpers/bigdata_helper.rb
module BigdataHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/contract_helper.rb
module ContractHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/views/about/_show.html.erb
<p class="side-nav-active-target">About This Website</h6>

<p>This website was created by myself using the Ruby on Rails framework. I utilized javascript and AJAX for the side bar navigation and the art paging to provide a smoother user experience. The art work paging was achieved via the kaminari gem. The front end is an extension of the Zurb Foundation Framework.</p>
<p></p>
<p class="bodyfontcolor">Thanks for visiting !!</p>

app/views/about/show.html.erb
<div id="artfolio-content">
  <%= render "show" %>
</div>

app/views/artfolio/_artwork.html.erb
<%= paginate @artworks, :remote => true %>
<P></P>
<% @artworks.each do |art| %>
  <img src=<%= art.url %> >
  <% if art.caption %>
    <p><%= art.caption %></p>
  <% end %>
<% end %>

app/views/artfolio/_navigation.html.erb
<h3 class="side-nav-color" >Art Folio</h3>
<ul class="side-nav">
  <li class="active" id="resume-oils1"><%= link_to "Oil Paintings", "/artfolio/index/oilpainting", remote: true %></li>
  <li class="side-nav-inactive" id="resume-drawings"><%= link_to "Drawings", "/artfolio/index/drawing", remote: true %></li>
</ul>
<p></p>
<p>The art works on this page were created by myself over the last ten years as a result of studies at the Art Student League in New York and the Chisel and Pallette Academy in Chicago. I hope you enjoy viewing them as much as I enjoyed producing them. Thanks for viewing !!</p>

app/views/artfolio/index.html.erb
<% content_for :navigation do %>
  <%= render "navigation" %>
<% end %>

<div id="artfolio-content">
  <%= render "artwork" %>
</div>

app/views/artfolio/index.js.erb
$("#artfolio-content").html("<%= escape_javascript(render "artwork") %>");

app/views/bigdata/_topnav.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="#">Big Data Project</a></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li class="divider"></li>
      <li class="active"><a href="#">Main Item 1</a></li>
      <li class="divider"></li>
      <li><a href="#">Main Item 2</a></li>
      <li class="divider"></li>
      <li class="has-dropdown"><a href="#">Main Item 3</a>

        <ul class="dropdown">
          <li class="has-dropdown"><a href="#">Dropdown Level 1a</a>

            <ul class="dropdown">
              <li><label>Dropdown Level 2 Label</label></li>
              <li><a href="#">Dropdown Level 2a</a></li>
              <li><a href="#">Dropdown Level 2b</a></li>
              <li class="has-dropdown"><a href="#">Dropdown Level 2c</a>

                <ul class="dropdown">
                  <li><label>Dropdown Level 3 Label</label></li>
                  <li><a href="#">Dropdown Level 3a</a></li>
                  <li><a href="#">Dropdown Level 3b</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Dropdown Level 3c</a></li>
                </ul>
              </li>
              <li><a href="#">Dropdown Level 2d</a></li>
              <li><a href="#">Dropdown Level 2e</a></li>
              <li><a href="#">Dropdown Level 2f</a></li>
            </ul>
          </li>
          <li><a href="#">Dropdown Level 1b</a></li>
          <li><a href="#">Dropdown Level 1c</a></li>
          <li class="divider"></li>
          <li><a href="#">Dropdown Level 1d</a></li>
          <li><a href="#">Dropdown Level 1e</a></li>
          <li><a href="#">Dropdown Level 1f</a></li>
          <li class="divider"></li>
          <li><a href="#">See all &rarr;</a></li>
        </ul>
      </li>
      <li class="divider"></li>
    </ul>

    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider hide-for-small"></li>
      <li class="has-dropdown"><a href="#">Main Item 4</a>

        <ul class="dropdown">
          <li><label>Dropdown Level 1 Label</label></li>
          <li class="has-dropdown"><a href="#" class="">Dropdown Level 1a</a>

            <ul class="dropdown">
              <li><a href="#">Dropdown Level 2a</a></li>
              <li><a href="#">Dropdown Level 2b</a></li>
              <li class="has-dropdown"><a href="#">Dropdown Level 2c</a>

                <ul class="dropdown">
                  <li><a href="#">Dropdown Level 3a</a></li>
                  <li><a href="#">Dropdown Level 3b</a></li>
                  <li><a href="#">Dropdown Level 3c</a></li>
                </ul>
              </li>
              <li><a href="#">Dropdown Level 2d</a></li>
              <li><a href="#">Dropdown Level 2e</a></li>
              <li><a href="#">Dropdown Level 2f</a></li>
            </ul>
          </li>
          <li><a href="#">Dropdown Level 1b</a></li>
          <li><a href="#">Dropdown Level 1c</a></li>
          <li class="divider"></li>
          <li><label>Dropdown Level 1 Label</label></li>
          <li><a href="#">Dropdown Level 1d</a></li>
          <li><a href="#">Dropdown Level 1e</a></li>
          <li><a href="#">Dropdown Level 1f</a></li>
          <li class="divider"></li>
          <li><a href="#">See all &rarr;</a></li>
        </ul>
      </li>
      <li class="divider"></li>
      <li class="has-form">
        <form>
          <div class="row collapse">
            <div class="small-8 columns">
              <input type="text">
            </div>
            <div class="small-4 columns">
              <a href="#" class="alert button">Search</a>
            </div>
          </div>
        </form>
      </li>
      <li class="divider show-for-small"></li>
      <li class="has-form">
        <a class="button" href="#">Button!</a>
      </li>
    </ul>
  </section>
</nav>

app/views/bigdata/index.html.erb
<%= render "topnav" %>
<h1>Projects</h1>
<p>Find me in app/views/bigdata/index.html.erb</p>

app/views/blogposts/_blogpost.html.erb
<article style="background-color:#E4ECF5">

  <div style="margin-left:10px">
    <h3><a href="#"><%= post.title %></a></h3>
    <h6>Written on <%= post.date %></h6>
    <div class="row">
      <div class="large-6 columns">
        <%= raw post.image_text %>
      </div>
      <div class="large-5 left columns">
        <img src=<%= post.image %> />
      </div>
    </div>
    <%= raw post.content %>
  </div>

</article>

app/views/blogposts/_blogposts.html.erb
<div class="large-8 columns" role="content">
  <% notfirst = false %>
  <% @blogposts.each do |post| %>
    <% if (notfirst) %>
      <hr/>
    <% end %>
    <% notfirst = true %>
    <%= render partial: "blogpost", locals: {post: post} %>
    <% if (@editable) %>
      <%= link_to 'Show', post %>
      <%= link_to 'Edit', edit_blogpost_path(post) %>
      <%= link_to 'NewPost', new_blogpost_path %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  <% end %>
</div>

app/views/blogposts/_form.html.erb
<%= form_for(@post) do |post_form| %>

  <div class="field">
    <%= post_form.label :title %><br />
    <%= post_form.text_field :title %>
  </div>
  <div class="field">
    <%= post_form.label :date %><br />
    <%= post_form.text_field :date %>
  </div>
  <div class="field">
    <%= post_form.label :image %><br />
    <%= post_form.text_field :image %>
  </div>
  <div class="field">
    <%= post_form.label :category %><br />
    <%= post_form.text_field :category %>
  </div>
  <div class="field">
    <%= post_form.label :image_text %><br />
    <%= post_form.text_area :image_text %>
  </div>
  <div class="field">
    <%= post_form.label :content %><br />
    <%= post_form.text_area :content %>
  </div>
  <div class="actions">
    <%= post_form.submit %>
  </div>

<% end %>

app/views/blogposts/_navigation.html.erb
<aside class="large-3 right columns">

  <h3 class="side-nav-color" >Categories</h3>
  <ul class="side-nav">
    <li class="active" id="resume-tech"><%= link_to "Technology", "/blogposts/display/tech", remote: true %></li>
    <li class="side-nav-inactive" id="resume-museum"><%= link_to "Museums", "/blogposts/display/museum", remote: true %></li>
    <li class="side-nav-inactive" id="resume-current"><%= link_to "Current Affairs", "/blogposts/display/current", remote: true %></li>
    <li class="side-nav-inactive" id="resume-general"><%= link_to "General Interest", "/blogposts/display/general", remote: true %></li>
  </ul>




</aside>

app/views/blogposts/display.html.erb
<div class="row">
  <div class="large-12 columns">
    <h2>Welcome to my Blog !!</h2>
    <h2><small>Not too much content here yet.</small></h2>
    <hr />
  </div>
</div>
  <!-- Main Blog Content -->

<div id="blogpost-content">
  <%= render "blogposts" %>
</div>

<!-- Sidebar -->
<%= render "navigation" %>

app/views/blogposts/display.js.erb
$("#blogpost-content").html("<%= escape_javascript(render "blogposts") %>");

app/views/blogposts/edit.html.erb
<h1>Editing post</h1>

<%= render partial: "blogpost", locals: {post: @post} %>

<%= render 'form' %>

<%= link_to 'Back', blogposts_path %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', blogposts_path %>

app/views/blogposts/index.html.erb
<!-- Main Blog Content -->
<% @editable=true %>
<div id="blogpost-content">
  <%= render "blogposts" %>
</div>

app/views/blogposts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', blogposts_path %>

app/views/blogposts/show.html.erb
<%= render partial: "blogpost", locals: {post: @post} %>

app/views/contact/_show.html.erb
<a href = "http://www.linkedin.com/pub/ronald-lump/76/684/82b" style="font-size:22px;text-decoration:underline">Contact Me on LinkedIn</a>

app/views/contact/show.html.erb
<div id="artfolio-content">
  <%= render "show" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr />
    <div class="row">
      <div class="large-6 columns">
        <p class="bodyfontcolor">&copy; 2013 Ronald P Lump All Rights Reserved </p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="/about/show">About</a></li>
          <li><a href="/contact/show">Contact Me</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="row top-bg-color">
  <div class="large-12 columns">
    <ul class="inline-list left">
      <li><a href="/resume/show"  style="color:tomato;font-size:30px;">Ronald P Lump</a></li>
    </ul>
    <ul class="inline-list right" style="font-size:22px;text-decoration:underline">
      <li><a href="/resume/show">Resume</a></li>
      <li><a href="/artfolio/index">ArtFolio</a></li>
      <li><a href="/blogposts/display">Blog</a></li>
    </ul>
  </div>
</div>

app/views/layouts/_onenavleft.html.erb
<div class="row" style="margin-top:44px;">
  <!-- Main Content Section -->
  <!-- This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens -->
  <div class="large-8 push-4 columns" style="margin-top:4px">
    <%= yield %>
  </div>


  <!-- Nav Sidebar -->
  <!-- This is source ordered to be pulled to the left on larger screens -->
  <div class="large-3 pull-9 columns side-nav-border side-nav-color" style="margin-bottom: 300px">
    <%= yield :navigation %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="page">
      <div id="header">
        <%= render "layouts/header" %>
      </div>
      <div id="main">
        <%= content_for?(:main_content) ? yield(:main_content) : (render "layouts/onenavleft") %>
      </div>
      <div id="footer">
        <%= render "layouts/footer" %>
      </div>
      <%= javascript_include_tag "application" %>
    </div>
  </body>

</html>

app/views/layouts/custom.html.erb
<%= content_for :main_content do %>

  <div class="row">

    <%= yield %>

  </div>

  <!-- End Main Content -->
<% end %>
<%= render template: "layouts/application" %>

app/views/layouts/nonavcenter.html.erb
<%= content_for :main_content do %>
  <div class="row" style="margin-top:44px;">
    <div class="large-8 push-2 columns" style="margin-top:4px">
      <%= yield %>
    </div>
  </div>
<% end %>
<%= render template: "layouts/application" %>

app/views/resume/_about.html.erb
<p class="side-nav-active-target">About me</h6>

<p>I am a software developer with 15 years industry experience. My most recent positon was developing backend exchange connectivity software for the trading industry in Chicago. Previous to that I developed web based diagnostic tools to assist systems engineers in managing the global network for Bloomberg LP in New York. Their network at that time was reputed to be the third largest private data network in the world. </p>

<p>My current goal is to return to web/internet related development. I see it as an exciting and dynamic field where I can use both my technical as well as creative skills. To assist in attaining this goal I recently completed a three month web development class at the Starter League in Chicago where I acquired new web development skills.</p>

<p>Please review the rest of this resume for a more detailed account of my professional development. When you have finished I would be pleased if you would view my <a href="/artfolio/index" style="text-decoration:underline">ArtFolio</a> containing works of art produced by myself. I hope they demonstrate my creative side and that you enjoy viewing them.</p>

<a href = "http://www.linkedin.com/pub/ronald-lump/76/684/82b" style="font-size:18px;text-decoration:underline">Contact Me on LinkedIn</a>

app/views/resume/_edu.html.erb
<p class="side-nav-active-target">Education</h6>

<p>University of New Mexico, Albuquerque, NM  — M.S. Computer Science</p>

<p>University of Illinois, Urbana, IL — B.S. Mechanical Engineering</p>

app/views/resume/_lang.html.erb
<p class="side-nav-active-target">Languages and Skills</h6>

<p>Languages: Ruby, C++, Javascript, AJAX, HTML, CSS</p>

<p>Operating System: Linux, Unix, Windows</p>

<p>Frameworks and Tools: RAILS, .NET, Boost, STL, SQL</p>

<p>Databases: relational, propietary</p>

app/views/resume/_navigation.html.erb
<h3 class="side-nav-color" >Resume</h3>
<ul class="side-nav">
  <li class="active" id="resume-about"><%= link_to "About Me", "/resume/about", remote: true %></li>
  <li class="side-nav-inactive" id="resume-lang"><%= link_to "Languages and Skills", "/resume/lang", remote: true %></li>
  <li class="side-nav-inactive" id="resume-work"><%= link_to "Recent Relevant Training", "/resume/relevant", remote: true %></li>
  <li class="side-nav-inactive" id="resume-work"><%= link_to "Work History", "/resume/work", remote: true %></li>
  <li class="side-nav-inactive" id="resume-edu"><%= link_to "Education", "/resume/edu", remote: true %></li>
</ul>

app/views/resume/_relevant.html.erb
<p class="side-nav-active-target">Recent Relevant Training</h6>

<p>Starter League, Chicago, IL April - June 2013</p>

<ul>
  <li>completed Starter League's web dev class where I reaquainted myself with the latest web technology by acquiring the skills needed to develop web applications with the Ruby on Rails framework</li>
  <li> participated in a class project to develop a facebook application that allows multi-user interactive photo album creation through a user's facebook login and the facebook developer API</li>
  <li> utilized AJAX, javascript, and jquery to provide a rich application interface and a positive user experience</li>
</ul>

<p>There are plans to continue with the development of the facebook photo album application and to go live sometime in future. Stay tuned !!</p>

app/views/resume/_work.html.erb
<p class="side-nav-active-target">Work History</h6>

<p>Systems Analyst, Archelon LLC, Chicago, IL April 2001 - Feb 2013</p>

<ul>
  <li>developed end to end real time low latency price servers where data is sourced from proprietary
  exchange tcp/udp feeds and delivery is the provision of fully decoded prices to database or to clients
  via tcp/udp or shared memory</li>
  <li> designed and developed order/quote routing libraries with an easy to use C++ object interface that
  managed exchange tcp trading sessions, packaged outgoing order/quotes, and decoded incoming responses</li>
  <li> developed a quote sharing application that aggregated quotes sourced from multiple clients and packaged and managed them as single quotes at the exchange</li>
  <li>implemented a real time data server for price delivery to MS Windows excel clients</li>
</ul>

<p>Software Developer, Bloomberg Financial Markets, New York, NY Oct 1997 - May 2000</p>

<ul>
  <li>developed WEB based diagnostic tool to statistically analyze traffic flow for a global wide network; backend was written in PERL and C++</li>
  <li>designed and configured a linux based system of servers to collect data from a global wide area network and statistically process data to serve to diagnostic clients</li>
  <li>participated in team development of  a WEB/JAVA end user application</li>
  <li>provided multimedia audio capabilities via Real Networks API to Windows multithreaded applications</li>
</ul>

<p>Senior Software Engineer, UCS, Inc, Golden CO Oct 1995 - June 1997</p>

<ul>
  <li>extended visual C++ to provide specialized view and document management</li>
  <li>explored and demonstrated varying GUI approaches to best present a user with a complex application</li>
  <li>aided in the development of an internally developed database that provided ODBC like connectivity</li>
  <li>project lead in the development of Windows based application to program Motorola two-way radios</li>
  <li>experience in scheduling software tasks for full first release of a software product</li>
</ul>

app/views/resume/about.js.erb
$("#resume-content").html("<%= escape_javascript(render "about") %>");

app/views/resume/edu.js.erb
$("#resume-content").html("<%= escape_javascript(render "edu") %>");

app/views/resume/lang.js.erb
$("#resume-content").html("<%= escape_javascript(render "lang") %>");

app/views/resume/relevant.js.erb
$("#resume-content").html("<%= escape_javascript(render "relevant") %>");

app/views/resume/show.html.erb
<% content_for :navigation do %>
  <%= render "navigation" %>
<% end %>

<div id="resume-content">
  <%= render "about" %>
</div>

app/views/resume/work.js.erb
$("#resume-content").html("<%= escape_javascript(render "work") %>");